spring.application.name=auth-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=${JPA_DDL:update}
spring.jpa.show-sql=true
server.port=8083

# Segurança JWT (Injetado obrigatoriamente via variável de ambiente JWT_SECRET)
api.security.token.secret=${JWT_SECRET}

# Mercado Pago Backend Token (Injetado via variável de ambiente MP_ACCESS_TOKEN)
mercadopago.access.token=${MP_ACCESS_TOKEN:}
