spring.application.name=auth-service

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8083

# Segurança JWT
api.security.token.secret=${JWT_SECRET:9839be35e537b9d52f59847cbe2c8bc2137c0b278eda29138bf67e53601a0999}

# Mercado Pago Backend Token (Access Token - pegar no painel do MP)
mercadopago.access.token=${MP_ACCESS_TOKEN:APP_USR-1102823162262805-071417-a5ff4c2745050a246686b5e52d7155ee-3089039441}
